DROP INDEX IF EXISTS idx_tmr_menuroute_mr_ssid_mr_mrid;
DROP TABLE IF EXISTS public.tmr_menuroute;

CREATE TABLE IF NOT EXISTS public.tmr_menuroute
(
    mr_mrid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    mr_ssid integer NOT NULL,
    mr_route character varying(64),
    mr_params JSONB,
    mr_search JSONB,
    CONSTRAINT tmr_menuroute_mr_mrid_key UNIQUE (mr_mrid)
);


CREATE INDEX idx_tmr_menuroute_mr_ssid_mr_mrid
ON public.tmr_menuroute (mr_ssid, mr_mrid);