DROP INDEX IF EXISTS idx_tml_menulinks_ml_ssid_ml_mlid;
DROP TABLE IF EXISTS public.tml_menulinks;

CREATE TABLE IF NOT EXISTS public.tml_menulinks
(
    ml_mlid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ml_ssid integer NOT NULL,
    ml_reference character varying(32),
    ml_url character varying(255),
    ml_path character varying(128),
    ml_segment character varying(16),
    ml_query character varying(255),
    ml_route character varying(32),
    CONSTRAINT tml_menulinks_ml_mlid_key UNIQUE (ml_mlid)
);

CREATE INDEX idx_tml_menulinks_ml_ssid_ml_mlid
ON public.tml_menulinks (ml_ssid, ml_mlid);