DROP TABLE IF EXISTS public.tdb_database;
CREATE TABLE IF NOT EXISTS public.tdb_database
(
    d_did integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    d_name character varying(16)  NOT NULL,
    CONSTRAINT tdb_database_pkey PRIMARY KEY (d_name)
);

DROP TABLE IF EXISTS public.tlr_library;
CREATE TABLE IF NOT EXISTS public.tlr_library
(
    lrlid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lrowner character varying(16)  NOT NULL,
    lrgroup character varying(32)  NOT NULL,
    lrref character varying(32)  NOT NULL,
    lrgid integer,
    lrdesc character varying ,
    lrlink character varying ,
    lrwho character varying ,
    lrtype character varying ,
    CONSTRAINT tlr_library_pkey PRIMARY KEY (lrowner, lrgroup, lrref),
    CONSTRAINT tlr_library_lrlid_key UNIQUE (lrlid)
);

DROP TABLE IF EXISTS public.tlg_logging;
CREATE TABLE IF NOT EXISTS public.tlg_logging
(
    lgid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lgfunctionname character varying  NOT NULL,
    lgsession integer NOT NULL,
    lgseverity character(1) ,
    lgmsg character varying  NOT NULL,
    lgdatetime timestamp without time zone NOT NULL,
    CONSTRAINT tlg_logging_lgid_key UNIQUE (lgid)
);

DROP TABLE IF EXISTS public.tow_owner;
CREATE TABLE IF NOT EXISTS public.tow_owner
(
    ooid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    oowner character varying(16)  NOT NULL,
    CONSTRAINT tow_owner_pkey PRIMARY KEY (oowner)
);

DROP TABLE IF EXISTS public.tog_ownergroup;
CREATE TABLE IF NOT EXISTS public.tog_ownergroup
(
    oggid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ogowner character varying(16)  NOT NULL,
    oggroup character varying(32)  NOT NULL,
    ogtitle character varying(50) ,
    ogcntquestions smallint DEFAULT 0,
    ogcntlibrary smallint DEFAULT 0,
    CONSTRAINT tog_ownergroup_pkey PRIMARY KEY (ogowner, oggroup),
    CONSTRAINT tog_ownergroup_oggid_key UNIQUE (oggid)
);

DROP TABLE IF EXISTS public.tqq_questions;
CREATE TABLE IF NOT EXISTS public.tqq_questions
(
    qqid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    qowner character varying(16)  NOT NULL,
    qgroup character varying(32)  NOT NULL,
    qgid integer NOT NULL,
    qseq smallint NOT NULL,
    qdetail character varying(256),
    qpoints integer[],
    qans text[] ,
    qrounds text[] ,
    qnorth text[] ,
    qeast text[] ,
    qsouth text[] ,
    qwest text[] ,
    qlid integer DEFAULT 0,
    CONSTRAINT tqq_questions_pkey PRIMARY KEY (qowner, qgroup, qseq),
    CONSTRAINT tqq_questions_qqid_key UNIQUE (qqid)
);

DROP TABLE IF EXISTS public.trf_reftype;
CREATE TABLE IF NOT EXISTS public.trf_reftype
(
    rtrid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    rttype character varying  NOT NULL,
    rttitle character varying(32) ,
    CONSTRAINT trf_reftype_pkey PRIMARY KEY (rttype),
    CONSTRAINT trf_reftype_rtrid_key UNIQUE (rtrid)
);

DROP TABLE IF EXISTS public.tss_sessions;
CREATE TABLE IF NOT EXISTS public.tss_sessions
(
    s_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    s_datetime timestamp without time zone NOT NULL,
    s_uid integer NOT NULL,
    CONSTRAINT tss_sessions_s_id_key UNIQUE (s_id)
);

DROP TABLE IF EXISTS public.tus_users;
CREATE TABLE IF NOT EXISTS public.tus_users
(
    u_uid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    u_name character varying(100) ,
    u_email text  NOT NULL,
    u_joined timestamp without time zone NOT NULL,
    u_fedid character varying(30) ,
    u_admin boolean,
    u_fedcountry character varying(16) ,
    u_provider character varying(30) ,
    u_sortquestions boolean DEFAULT true,
    u_skipcorrect boolean DEFAULT true,
    u_maxquestions integer DEFAULT 5,
    CONSTRAINT tus_users_pkey PRIMARY KEY (u_uid),
    CONSTRAINT tus_users_u_email_key UNIQUE (u_email)
);

DROP TABLE IF EXISTS public.ths_usershistory;
CREATE TABLE IF NOT EXISTS public.ths_usershistory
(
    r_hid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    r_datetime timestamp without time zone NOT NULL,
    r_gid integer,
    r_owner character varying(16)  NOT NULL,
    r_group character varying(32) ,
    r_qid integer[],
    r_questions integer,
    r_ans integer[],
    r_points integer[],
    r_maxpoints integer,
    r_totalpoints integer,
    r_correctpercent integer,
    r_uid integer,
    r_sid integer DEFAULT 0,
    CONSTRAINT ths_usershistory_r_hid_key UNIQUE (r_hid)
);

DROP TABLE IF EXISTS public.tuo_usersowner;
CREATE TABLE IF NOT EXISTS public.tuo_usersowner
(
    uouid integer NOT NULL,
    uoowner character varying(32)  NOT NULL,
    CONSTRAINT tuo_usersowner_pkey PRIMARY KEY (uouid, uoowner)
);

DROP TABLE IF EXISTS public.tup_userspwd;
CREATE TABLE IF NOT EXISTS public.tup_userspwd
(
    upuid integer NOT NULL,
    uphash character varying(100) ,
    upemail text ,
    CONSTRAINT tup_userspwd_pkey PRIMARY KEY (upuid)
);

DROP TABLE IF EXISTS public.twh_who;
CREATE TABLE IF NOT EXISTS public.twh_who
(
    wwid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    wwho character varying(16)  NOT NULL,
    wtitle character varying(32) ,
    CONSTRAINT twh_who_pkey PRIMARY KEY (wwho),
    CONSTRAINT twh_who_wwid_key UNIQUE (wwid)
);
