DROP TABLE IF EXISTS public.z_1database;
CREATE TABLE IF NOT EXISTS public.z_1database
(
    d_did integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    d_name character varying(16)  NOT NULL,
    CONSTRAINT z_1database_pkey PRIMARY KEY (d_name)
);

DROP TABLE IF EXISTS public.z_1library;
CREATE TABLE IF NOT EXISTS public.z_1library
(
    lrlid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lrowner character varying(16)  NOT NULL,
    lrgroup character varying(32)  NOT NULL,
    lrref character varying(32)  NOT NULL,
    lrgid integer,
    lrdesc character varying ,
    lrlink character varying ,
    lrwho character varying ,
    lrtype character varying ,
    CONSTRAINT z_1library_pkey PRIMARY KEY (lrowner, lrgroup, lrref),
    CONSTRAINT z_1library_lrlid_key UNIQUE (lrlid)
);

DROP TABLE IF EXISTS public.z_1logging;
CREATE TABLE IF NOT EXISTS public.z_1logging
(
    lgid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lgfunctionname character varying  NOT NULL,
    lgsession integer NOT NULL,
    lgseverity character(1) ,
    lgmsg character varying  NOT NULL,
    lgdatetime timestamp without time zone NOT NULL,
    CONSTRAINT z_1logging_lgid_key UNIQUE (lgid)
);

DROP TABLE IF EXISTS public.z_1owner;
CREATE TABLE IF NOT EXISTS public.z_1owner
(
    ooid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    oowner character varying(16)  NOT NULL,
    CONSTRAINT z_1owner_pkey PRIMARY KEY (oowner)
);

DROP TABLE IF EXISTS public.z_1ownergroup;
CREATE TABLE IF NOT EXISTS public.z_1ownergroup
(
    oggid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ogowner character varying(16)  NOT NULL,
    oggroup character varying(32)  NOT NULL,
    ogtitle character varying(50) ,
    ogcntquestions smallint DEFAULT 0,
    ogcntlibrary smallint DEFAULT 0,
    CONSTRAINT z_1ownergroup_pkey PRIMARY KEY (ogowner, oggroup),
    CONSTRAINT z_1ownergroup_oggid_key UNIQUE (oggid)
);

DROP TABLE IF EXISTS public.z_1questions;
CREATE TABLE IF NOT EXISTS public.z_1questions
(
    qqid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    qowner character varying(16)  NOT NULL,
    qgroup character varying(32)  NOT NULL,
    qgid integer NOT NULL,
    qseq smallint NOT NULL,
    qdetail character varying(256),
    qpoints integer[],
    qans text[] ,
    qrounds text[] ,
    qnorth text[] ,
    qeast text[] ,
    qsouth text[] ,
    qwest text[] ,
    CONSTRAINT z_1questions_pkey PRIMARY KEY (qowner, qgroup, qseq),
    CONSTRAINT z_1questions_qqid_key UNIQUE (qqid)
);

DROP TABLE IF EXISTS public.z_1reftype;
CREATE TABLE IF NOT EXISTS public.z_1reftype
(
    rtrid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    rttype character varying  NOT NULL,
    rttitle character varying(32) ,
    CONSTRAINT z_1reftype_pkey PRIMARY KEY (rttype),
    CONSTRAINT z_1reftype_rtrid_key UNIQUE (rtrid)
);

DROP TABLE IF EXISTS public.z_1sessions;
CREATE TABLE IF NOT EXISTS public.z_1sessions
(
    s_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    s_datetime timestamp without time zone NOT NULL,
    s_uid integer NOT NULL,
    s_sortquestions boolean DEFAULT true,
    s_skipcorrect boolean DEFAULT true,
    s_dftmaxquestions integer DEFAULT 20,
    CONSTRAINT z_1sessions_s_id_key UNIQUE (s_id)
);

DROP TABLE IF EXISTS public.z_1users;
CREATE TABLE IF NOT EXISTS public.z_1users
(
    u_uid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    u_name character varying(100) ,
    u_email text  NOT NULL,
    u_joined timestamp without time zone NOT NULL,
    u_fedid character varying(30) ,
    u_admin boolean,
    u_fedcountry character varying(16) ,
    u_provider character varying(30) ,
    CONSTRAINT z_1users_pkey PRIMARY KEY (u_uid),
    CONSTRAINT z_1users_u_email_key UNIQUE (u_email)
);

DROP TABLE IF EXISTS public.z_1usershistory;
CREATE TABLE IF NOT EXISTS public.z_1usershistory
(
    r_hid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    r_datetime timestamp without time zone NOT NULL,
    r_gid integer,
    r_owner character varying(16)  NOT NULL,
    r_group character varying(32) ,
    r_qid integer[],
    r_questions integer,
    r_ans integer[],
    r_points integer[],
    r_maxpoints integer,
    r_totalpoints integer,
    r_correctpercent integer,
    r_uid integer,
    r_sid integer DEFAULT 0,
    CONSTRAINT z_1usershistory_r_hid_key UNIQUE (r_hid)
);

DROP TABLE IF EXISTS public.z_1usersowner;
CREATE TABLE IF NOT EXISTS public.z_1usersowner
(
    uouid integer NOT NULL,
    uoowner character varying(32)  NOT NULL,
    CONSTRAINT z_1usersowner_pkey PRIMARY KEY (uouid, uoowner)
);

DROP TABLE IF EXISTS public.z_1userspwd;
CREATE TABLE IF NOT EXISTS public.z_1userspwd
(
    upuid integer NOT NULL,
    uphash character varying(100) ,
    upemail text ,
    CONSTRAINT z_1userspwd_pkey PRIMARY KEY (upuid)
);

DROP TABLE IF EXISTS public.z_1who;
CREATE TABLE IF NOT EXISTS public.z_1who
(
    wwid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    wwho character varying(16)  NOT NULL,
    wtitle character varying(32) ,
    CONSTRAINT z_1who_pkey PRIMARY KEY (wwho),
    CONSTRAINT z_1who_wwid_key UNIQUE (wwid)
);
