ALTER TABLE public.library ALTER COLUMN lrlid RESTART WITH 1000;
delete from tlg_logging;
ALTER TABLE public.tlg_logging ALTER COLUMN lg_lgid RESTART WITH 1000;
ALTER TABLE public.owner ALTER COLUMN ow_owid RESTART WITH 1000;
ALTER TABLE public.subject ALTER COLUMN sb_sbid RESTART WITH 1000;
ALTER TABLE public.tqq_questions ALTER COLUMN qq_qqid RESTART WITH 1000;
ALTER TABLE public.reftype ALTER COLUMN rt_rtid RESTART WITH 1000;
delete from tss_sessions;
ALTER TABLE public.tss_sessions ALTER COLUMN ss_ssid RESTART WITH 1000;
ALTER TABLE public.users ALTER COLUMN us_usid RESTART WITH 1000;
ALTER TABLE public.usershistory ALTER COLUMN hs_hsid RESTART WITH 1000;
ALTER TABLE public.who ALTER COLUMN wh_whid RESTART WITH 1000;
