ALTER TABLE public.library ALTER COLUMN lrlid RESTART WITH 1000;
delete from tlg_logging;
ALTER TABLE public.tlg_logging ALTER COLUMN lg_id RESTART WITH 1000;
ALTER TABLE public.owner ALTER COLUMN ow_oid RESTART WITH 1000;
ALTER TABLE public.subject ALTER COLUMN sb_sid RESTART WITH 1000;
ALTER TABLE public.tqq_questions ALTER COLUMN qq_qid RESTART WITH 1000;
ALTER TABLE public.reftype ALTER COLUMN rt_rid RESTART WITH 1000;
delete from tss_sessions;
ALTER TABLE public.tss_sessions ALTER COLUMN ss_id RESTART WITH 1000;
ALTER TABLE public.users ALTER COLUMN us_uid RESTART WITH 1000;
ALTER TABLE public.usershistory ALTER COLUMN hs_hid RESTART WITH 1000;
ALTER TABLE public.who ALTER COLUMN wh_wid RESTART WITH 1000;
