CREATE TABLE IF NOT EXISTS public.tdb_database
(
    db_dbid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    db_name character varying(16) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tdb_database_pkey PRIMARY KEY (db_name)
)

CREATE TABLE IF NOT EXISTS public.ths_history
(
    hs_hsid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    hs_datetime timestamp with time zone NOT NULL,
    hs_sbid integer,
    hs_owner character varying(16) COLLATE pg_catalog."default" NOT NULL,
    hs_subject character varying(32) COLLATE pg_catalog."default",
    hs_qqid integer[],
    hs_questions integer,
    hs_ans integer[],
    hs_points integer[],
    hs_maxpoints integer,
    hs_totalpoints integer,
    hs_correctpercent integer,
    hs_usid integer,
    hs_rfid integer DEFAULT 0,
    CONSTRAINT ths_history_hs_hsid_key UNIQUE (hs_hsid)
)

CREATE TABLE IF NOT EXISTS public.tlg_logging
(
    lg_lgid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    lg_severity character(1) COLLATE pg_catalog."default",
    lg_caller character varying COLLATE pg_catalog."default" DEFAULT ''::character varying,
    lg_functionname character varying COLLATE pg_catalog."default" NOT NULL,
    lg_msg character varying COLLATE pg_catalog."default" NOT NULL,
    lg_datetime timestamp without time zone NOT NULL,
    CONSTRAINT tlg_logging_lg_lgid_key UNIQUE (lg_lgid)
)

CREATE TABLE IF NOT EXISTS public.tow_owner
(
    ow_owid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ow_owner character varying(16) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tow_owner_pkey PRIMARY KEY (ow_owner)
)

CREATE TABLE IF NOT EXISTS public.tqq_questions
(
    qq_qqid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    qq_owner character varying(16) COLLATE pg_catalog."default" NOT NULL,
    qq_subject character varying(32) COLLATE pg_catalog."default" NOT NULL,
    qq_sbid integer NOT NULL,
    qq_seq smallint NOT NULL,
    qq_detail character varying(256) COLLATE pg_catalog."default",
    qq_points integer[],
    qq_ans text[] COLLATE pg_catalog."default",
    qq_rounds text[] COLLATE pg_catalog."default",
    qq_north text[] COLLATE pg_catalog."default",
    qq_east text[] COLLATE pg_catalog."default",
    qq_south text[] COLLATE pg_catalog."default",
    qq_west text[] COLLATE pg_catalog."default",
    qq_rfid integer DEFAULT 0,
    qq_help text COLLATE pg_catalog."default",
    CONSTRAINT tqq_questions_pkey PRIMARY KEY (qq_owner, qq_subject, qq_seq),
    CONSTRAINT tqq_questions_qq_qqid_key UNIQUE (qq_qqid)
)

CREATE TABLE IF NOT EXISTS public.trf_reference
(
    rf_rfid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    rf_owner character varying(16) COLLATE pg_catalog."default" NOT NULL,
    rf_subject character varying(32) COLLATE pg_catalog."default" NOT NULL,
    rf_ref character varying(32) COLLATE pg_catalog."default" NOT NULL,
    rf_sbid integer,
    rf_desc character varying COLLATE pg_catalog."default",
    rf_link character varying COLLATE pg_catalog."default",
    rf_who character varying COLLATE pg_catalog."default",
    rf_type character varying COLLATE pg_catalog."default",
    rf_cntquestions smallint DEFAULT 0,
    CONSTRAINT trf_reference_pkey PRIMARY KEY (rf_owner, rf_subject, rf_ref),
    CONSTRAINT trf_reference_rf_rfid_key UNIQUE (rf_rfid)
)

CREATE TABLE IF NOT EXISTS public.trt_reftype
(
    rt_rtid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    rt_type character varying COLLATE pg_catalog."default" NOT NULL,
    rt_title character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT trt_reftype_pkey PRIMARY KEY (rt_type),
    CONSTRAINT trt_reftype_rt_rtid_key UNIQUE (rt_rtid)
)

CREATE TABLE IF NOT EXISTS public.tsb_subject
(
    sb_sbid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sb_owner character varying(16) COLLATE pg_catalog."default" NOT NULL,
    sb_subject character varying(32) COLLATE pg_catalog."default" NOT NULL,
    sb_title character varying(50) COLLATE pg_catalog."default",
    sb_cntquestions smallint DEFAULT 0,
    sb_cntreference smallint DEFAULT 0,
    CONSTRAINT tsb_subject_pkey PRIMARY KEY (sb_owner, sb_subject),
    CONSTRAINT tsb_subject_sb_sbid_key UNIQUE (sb_sbid)
)

CREATE TABLE IF NOT EXISTS public.tss_sessions
(
    ss_ssid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ss_datetime timestamp with time zone NOT NULL,
    ss_usid integer NOT NULL,
    CONSTRAINT tss_sessions_ss_ssid_key UNIQUE (ss_ssid)
)

CREATE TABLE IF NOT EXISTS public.tuf_friends
(
    uf_usid integer NOT NULL,
    uf_frid integer NOT NULL,
    CONSTRAINT tuf_friends_pkey PRIMARY KEY (uf_usid, uf_frid)
)

CREATE TABLE IF NOT EXISTS public.tuo_usersowner
(
    uo_usid integer NOT NULL,
    uo_owner character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tuo_usersowner_pkey PRIMARY KEY (uo_usid, uo_owner)
)

CREATE TABLE IF NOT EXISTS public.tup_userspwd
(
    up_usid integer NOT NULL,
    up_hash character varying(100) COLLATE pg_catalog."default",
    up_email text COLLATE pg_catalog."default",
    CONSTRAINT tup_userspwd_pkey PRIMARY KEY (up_usid)
)

CREATE TABLE IF NOT EXISTS public.tus_users
(
    us_usid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    us_name character varying(100) COLLATE pg_catalog."default",
    us_email text COLLATE pg_catalog."default" NOT NULL,
    us_joined timestamp with time zone NOT NULL,
    us_fedid character varying(30) COLLATE pg_catalog."default",
    us_admin boolean,
    us_fedcountry character varying(16) COLLATE pg_catalog."default",
    us_provider character varying(30) COLLATE pg_catalog."default",
    us_skipcorrect boolean DEFAULT true,
    us_maxquestions integer DEFAULT 5,
    us_graph_user_months integer NOT NULL DEFAULT 24,
    us_graph_top_months integer NOT NULL DEFAULT 24,
    us_graph_recent_users integer NOT NULL DEFAULT 5,
    us_graph_recent_avg integer NOT NULL DEFAULT 5,
    CONSTRAINT tus_users_pkey PRIMARY KEY (us_usid),
    CONSTRAINT tus_users_us_email_key UNIQUE (us_email)
)

CREATE TABLE IF NOT EXISTS public.twh_who
(
    wh_whid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    wh_who character varying(16) COLLATE pg_catalog."default" NOT NULL,
    wh_title character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT twh_who_pkey PRIMARY KEY (wh_who),
    CONSTRAINT twh_who_wh_whid_key UNIQUE (wh_whid)
)

